### ISSUE TITLE
Archive of this repo.

### ISSUE THREAD

**Issue by SantoshNC68** [eiffel-community/eiffel-remrem-shared#30]
### Description
Clean this repo, as there is no dependency to this repo in other REMReM components.

### Motivation
Dead repository, not in use.

### Benefits
Clear the dead code/repositories for better understanding and maintainability.

### Possible Drawbacks
 None.

**Comment by m-linner-ericsson** [comment]
It should be archived:
* Update the readme and add the https://github.com/eiffel-community/community/blob/master/PROJECT_LIFECYCLE.md#stage-archived badge
* Update https://github.com/eiffel-community/community/blob/master/PROJECTS.md and change status to archived (if it is there)
* Close this issue
* Archive the project

**Comment by m-linner-ericsson** [comment]
Before setting this to archived we need to remove all references to it. See https://github.com/eiffel-community/eiffel-remrem-publish/blob/master/pom.xml#L13 and https://github.com/eiffel-community/eiffel-remrem-generate/blob/master/pom.xml#L14.

**Comment by m-linner-ericsson** [comment]
But the project is still not archived: @RajuBeemreddy1 @jainadc9
